[project]
name = "whisper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ctranslate2==4.6.2",
    "faster-whisper==1.2.1",
    "psutil==7.2.1",
    "pyside6==6.10.1",
    "sounddevice==0.5.3",
]
